version: '3.3'

services:
    jenkins:
        container_name: jenkins
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
            JAVA_OPTS: "-Xmx2048m -XX:MaxPermSize=512m"
            CASC_JENKINS_CONFIG: /var/jenkins_home/casc_configs
        hostname: jenkins
        image: ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/jenkins/${JENKINS_VERSION:-2.150.3}:${CONTAINER_TAG:-latest}
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        ports:
            - 8080:8080
        volumes:
            - ~/test/jenkins_home:/var/jenkins_home
            - ~/test/casc_configs:/var/jenkins_home/casc_configs
            - ~/test/ssl:/usr/local/share/ca-certificates
            - ~/test/log:/var/log/jenkins
            - ~/.ssh:/var/ssh
            - /var/run/docker.sock:/var/run/docker.sock
            - /usr/bin/docker:/usr/bin/docker
