apiVersion: v1
kind: Pod
metadata:
  name: jenkins-slave
  labels:
    jenkins-label: POD_LABEL
spec:
  containers:
  - name: jnlp
    image: jenkins/jnlp-slave:3.35-5-alpine
    args: [ '-url', '\${JENKINS_URL}', '\$(JENKINS_SECRET)', '\$(JENKINS_NAME)' ]
    tty: true
