apiVersion: v1
kind: Pod
metadata:
  name: jenkins-slave
  namespace: jenkins
  labels:
    jenkins-label: POD_LABEL
spec:
  ttlSecondsAfterFinished: 120
  containers:
  - name: jnlp
    image: s2.ubuntu.home:5000/thirdparty/jenkins/inbound-agent:4.3-9-alpine
    imagePullPolicy: Always
    volumeMounts:
    - name: workspace-volume
      mountPath: /home/jenkins
    - name: ca-pemstore
      readOnly: true
      mountPath: /etc/ssl/certs/soho-ball.crt
      subPath: soho-ball.crt
  volumes:
  - name: ca-pemstore
    configMap:
      name: ca-pemstore
      items:
      - key: soho-ball.pem
        path: soho-ball.crt
  restartPolicy: Never
