apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: POD_LABEL
spec:
  containers:
  - name: jnlp
    image: jenkins/jnlp-slave:3.35-5-alpine
    args: ['\$(JENKINS_SECRET)', '\$(JENKINS_NAME)']
    tty: true
