apiVersion: v1
kind: Pod
metadata:
  name: jenkins-slave
  namespace: jenkins
  labels:
    jenkins-label: POD_LABEL
spec:
  hostAliases:
  - ip: "10.3.1.10"
    hostnames:
    - "s3.ubuntu.home"
  containers:
  - name: jnlp
    image: s2.ubuntu.home:5000/alpine/jenkins/inbound-agent/3283.v92c105e0f819-8-alpine-jdk21:latest
    imagePullPolicy: Always
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 1
        memory: 1Gi
    securityContext:
        runAsUser: 1000
    stdin: true
    tty: true
    volumeMounts:
    - name: workspace-volume
      mountPath: /home/jenkins/agent
  restartPolicy: Never
#  ttlSecondsAfterFinished: 120
  volumes:
  - name: workspace-volume
    emptyDir: {}
