apiVersion: v1
kind: Pod
metadata:
  name: jenkins-slave
  namespace: jenkins
  labels:
    jenkins-label: POD_LABEL
spec:
  containers:
  - name: jnlp
    image: s2.ubuntu.home:5000/thirdparty/jenkins/inbound-agent:home
    imagePullPolicy: Always
    resources: 
      limits: 
        cpu: 1
        memory: 1Gi
      requests: 
        cpu: 1
        memory: 1Gi
    stdin: true
    user: root
    tty: true 
    volumeMounts:
    - name: workspace-volume
      mountPath: /home/jenkins/agent
  restartPolicy: Never
  ttlSecondsAfterFinished: 120
  volumes:
  - name: workspace-volume
    emptyDir: {} 
